default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: uranai_app_development

test:
  <<: *default
  database: uranai_app_test

production:
  <<: *default
  database: uranai_app_production
  username: uranai_app
  password: <%= ENV['URANAI_APP_DATABASE_PASSWORD'] %>
